# Generated by Django 3.0.3 on 2020-02-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('student', 'Student'), ('teacher', 'Teacher'), ('elder', 'Elder'), ('admin', 'Administrator')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(choices=[('amiskwaciy', 'Amiskwaciy Academy'), ('nait', 'NAIT')], default='amiskwaciy', max_length=20),
        ),
    ]
