# Generated by Django 3.0.3 on 2020-02-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200220_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(choices=[('Amiskwaciy Academy', 'Amiskwaciy Academy'), ('NAIT', 'NAIT')], default='amiskwaciy', max_length=20),
        ),
    ]
