# Generated by Django 3.0.3 on 2020-03-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200226_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(choices=[('Amiskwaciy Academy', 'Amiskwaciy Academy'), ('NAIT', 'NAIT')], default='amiskwaciy', max_length=100),
        ),
    ]
