# Generated by Django 3.0.3 on 2020-03-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='school',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
