# Generated by Django 3.0.4 on 2020-03-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20200317_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
