# Generated by Django 3.0.4 on 2020-03-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20200318_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='category',
            field=models.CharField(choices=[('Emotional', 'Emotional'), ('Mental', 'Mental'), ('Physical', 'Physical'), ('Spiritual', 'Spiritual')], default='NOT SET', max_length=100),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='school',
            field=models.CharField(choices=[('Amiskwaciy-Academy', 'Amiskwaciy Academy'), ('NAIT', 'NAIT')], default='NOT SET', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
